<Project>

  <PropertyGroup Label="Build conventions">
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Label="Metadata">
    <Authors>Victor Buzin</Authors>
    <Company>techbuzzz</Company>
    <Product>WatermarkRemover</Product>
    <Copyright>Copyright (c) 2026 Victor Buzin</Copyright>
    <LicenseExpression>MIT</LicenseExpression>
    <RepositoryUrl>https://github.com/techbuzzz/ai-watermark-remover</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/techbuzzz/ai-watermark-remover</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

</Project>